server:
  port: 8088
  servlet:
    context-path: /paperx
  #设置控制台日志级别
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
#日志级别配置
logging:
  level:
    org.springframework.web: DEBUG        #Spring框架中的日志级别
                                         #自己项目包
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paperx?characterEncoding=utf-8&useSSL=false
    username: root
    password: dkyabc

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.paperx.bgbackup.model
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


